{% set name = "gofumpt" %}
{% set version = "0.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/mvdan/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 0fe46851740bc4146f1e2ac0b23ca67a481490a603db189cae35a4be1787092f

build:
  number: 0

requirements:
  build:
    - {{ compiler('go-nocgo') }}
    - go-licenses

test:
  commands:
    - {{ name }} --help

about:
  home: https://github.com/mvdan/{{ name }}
  license: BSD-3-Clause
  license_file:
    - LICENSE
    - license-files/
  summary: Stricter gofmt
  dev_url: https://github.com/mvdan/{{ name }}

extra:
  recipe-maintainers:
    - danielnachun
