{% set name = "gofumpt" %}
{% set version = "0.9.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/mvdan/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 43cc77a94f65b2ba940310ac4268567d61b9cc01414b0c70cce45c5a60c8e4ec

build:
  number: 0

requirements:
  build:
    - {{ compiler('go-nocgo') }}
    - go-licenses

test:
  commands:
    - {{ name }} --help

about:
  home: https://github.com/mvdan/{{ name }}
  license: BSD-3-Clause
  license_file:
    - LICENSE
    - license-files/
  summary: Stricter gofmt
  dev_url: https://github.com/mvdan/{{ name }}

extra:
  recipe-maintainers:
    - danielnachun
