{% set name = "gofumpt" %}
{% set version = "0.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/mvdan/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 4e0e23832e74779ca0fa6af8ca7c15dbf20599dec34c8c96607b9b2e59157cb7

build:
  number: 0

requirements:
  build:
    - {{ compiler('go-nocgo') }}
    - go-licenses

test:
  commands:
    - {{ name }} --help

about:
  home: https://github.com/mvdan/{{ name }}
  license: BSD-3-Clause
  license_file:
    - LICENSE
    - license-files/
  summary: Stricter gofmt
  dev_url: https://github.com/mvdan/{{ name }}

extra:
  recipe-maintainers:
    - danielnachun
